### ISSUE TITLE
replacing prop by custom getter, setter

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [ciscoheat/mithril-hx#16]
If I understand correctly, we use M.prop so that we later can replace these with custom getter/setter functions if neede. Correct?

What is the way of doing this when it actually happens? If I just replace the property by a haxe property with custom get/set functions, the syntax for access changes.

**Comment by ciscoheat** [comment]
I don't think accessor substitution is an indented usage for `M.prop`. As you say they have different types, though the name *GetterSetter* may be confusing. 

They are just another way of handling data, for example it's convenient to pass the GetterSetter to a promise call:

```haxe
var prop = M.prop("");
// Sets the value of prop when the request finishes:
M.request({method: "GET", url: "/get/value/from/server"}).then(prop);
```

`M.request` actually returns a GetterSetter for immediate usage, but unfortunately I cannot express this in Haxe since the returned object is also a Promise. But it still works if you cast it:

```haxe
// Sets the value of prop when the request finishes:
var prop : GetterSetter<String> = cast M.request({method: "GET", url: "/get/value/from/server"}).then(prop);
```

**Comment by RudolfVonKrugstein** [comment]
MMh, ok. but isn't being able to replace it by a get/set function a useful use case?

If I am interpreting [this](http://lhorie.github.io/mithril-blog/the-uniform-access-principle.html) correctly it is one of the intended use cases (or at least a possible use case).

What about:
```
function propGetSet(get : Void -> T, set : T -> T) {
  return function(?v : T) {
    if (v == null) return get();
   else              return set(v);
  }
}
```

I am very new to mithril, and its concepts, so I am wondering if this really make sense from the design principle point of view ...

**Comment by ciscoheat** [comment]
I was confused at first because a use case to me is a step description related to actual users, instead of all the crazy things we programmers can do behind the scenes. :) I wouldn't do it like that though, if the getter/setter can hide what really happens it will be hard to understand the program, and is basically a violation of encapsulation (like any getter/setter can be).

**Comment by RudolfVonKrugstein** [comment]
ok, thanks!
