### ISSUE TITLE
How to handle sub-components

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [ciscoheat/mithril-hx#18]
Looking at this mithril example: https://lhorie.github.io/mithril/components.html I see that in original mithril components are nested like this:

```
view: function(ctrl) {
        return [
            m.component(ContactForm, {onsave: ctrl.save}),
            m.component(ContactList, {contacts: ctrl.contacts})
        ]
    }
```

How should this be done in mithril-hx? Should I just say "new ContactForm"? But then every time view is executed a now contact form is created. Should I have a "ContactForm" propertie in my main component?

**Comment by ciscoheat** [comment]
Hey! Yes, we've discussed that a little in [this issue](https://github.com/ciscoheat/mithril-hx/issues/11#issuecomment-120985297), and in my last comment I'm leaning towards not using the component stuff when using Haxe.

The reason is related to what you say, when you already have a ContactForm in your main component (both of them ordinary Haxe objects). Then it's redundant to call `m.component`, since it's basically works as a factory, but if you have already instantiated it, it's not needed and you can use `contactForm.view()` instead.

Everything works very well when you treat your objects as any combination of M, V and C. The `view` method is just a method outputting a template, the real MVC View is the object itself, and it can contain other objects.
