### ISSUE TITLE
Calling controllers

### ISSUE THREAD

**Issue by benmerckx** [ciscoheat/mithril-hx#23]
I'm trying to achieve something like this:

```haxe
class Test implements Component {
	public function new() {}
	public function controller() {
		trace('ok');
	}
	public function view() {return m('');}
}

class TestApp implements Component {
	var comp: Component;
	public function new() {}
	public function controller() {}
	public function setView(comp) {
		this.comp = comp;
	}
	public function view() 
		return m('.app', {}, M.component(comp));
}

class Main {
	static function main() {
		var a = new Test();
		var b = new Test();
		var test = new TestApp();
		test.setView(a);
		M.mount(Browser.document.body, test);
		test.setView(b);
		M.redraw(true);
		test.setView(a);
		M.redraw(true);
	}
}
```
Running the example above traces 'ok' only once, where I would expect it to run for each time I change the view. I don't really know if this is the right way to go about doing something like this, or if there really is a problem with mithril or the externs. Maybe you could point me in the right direction?

**Comment by ciscoheat** [comment]
I think it's the expected behavior, since you're bypassing Mithril's `controller` handling when creating the `Test`  objects yourself and assigning them in a normal Haxe class. If you use routes, you may get a different result since all controllers are called again when the route changes.

The more I use mithril-hx, the less I'm relying on the `controller` method, since it works as a constructor in Mithril, which we already have with Haxe's classes.

**Comment by benmerckx** [comment]
Using the router works as expected, but in this case it's not a good fit. I'm using it for developing a cordova app, where I have no use for routing really. I mainly use the controller method in cases where I need some stuff done when the components mounts/unmounts (for example adding/removing an event listener to the window object). The combination of controller/unonload is really useful for that. I could replace it by using config on the root element of the view (with ctx.onunload), but that means I'm relying on the component to be rendered first. So I'm unsure what the right way to do this would be.

**Comment by ciscoheat** [comment]
Ok, I see! Looking at https://lhorie.github.io/mithril/mithril.component.html#unloading-components it seems that you have to call `mount` again to make your case work, instead of using `redraw` (which is only view-related). Does it work to replace the `M.redraw` calls in your example with the same `M.mount` call?

**Comment by benmerckx** [comment]
Thanks, I see. I've misinterpreted the use of the controller method. I've solved this for my case by calling a mount/unmount method on the components since they all pass through the same method. Something like this:
```haxe
public function setView(view) {
  if (component != null) component.unmount();
  component = view;
  component.mount();
}
```
Thanks for the help and your work on the externs!

**Comment by ciscoheat** [comment]
Glad to help. :)
