### ISSUE TITLE
component args not passed to view nor controller

### ISSUE THREAD

**Issue by postite** [ciscoheat/mithril-hx#27]
hello,

id ont get why args from the M.component method don't get passed to view nor controller as said in the doc.
perhaps i'm doing something wrong .. i'm just starting to understand how mithril works.

```
return M.component(new ShopItemView(i),{message:"hello"});
```

with this:

```
class ShopItemView implements Mithril{
var item:Track;
public function new(item:Track){
    this.item=item;
    this.signal=signal;
    trace(" new Shopitem");
}
public function controller(?args{message:String}){


}
public function view(?ctrl ,?args:{message:String}){
    return m('.vide',args.message+item.title);

}
```

}

**Comment by ciscoheat** [comment]
Hi, the `component` method is Mithril's way of instantiating objects in a view. Since Haxe has its own classes, I understand your confusion. I recommend not to use `M.component`, instead store the state you need as member fields in the class, and use them in the `view` method.

So in your example, pass the message to the `ShopItemView` constructor instead, and display it in the view. The `ctrl` argument will be `this`, so you don't need any arguments actually.

The `controller` method is useful mostly when you're using routes. Any change of route will call `controller` in the object for the new route.
